Repository GEOS-DEV/geosPythonPackages, pull requests merged in 2025-04, with the labels that each got.

#68 Add module path to sys path for PVplugins
  geos-posp/src/PVplugins/PVAttributeMapping.py
  geos-posp/src/PVplugins/PVCreateConstantAttributePerRegion.py
  geos-posp/src/PVplugins/PVExtractMergeBlocksVolume.py
  geos-posp/src/PVplugins/PVExtractMergeBlocksVolumeSurface.py
  geos-posp/src/PVplugins/PVExtractMergeBlocksVolumeSurfaceWell.py
  geos-posp/src/PVplugins/PVExtractMergeBlocksVolumeWell.py
  geos-posp/src/PVplugins/PVGeomechanicsAnalysis.py
  geos-posp/src/PVplugins/PVGeomechanicsWorkflowVolume.py
  geos-posp/src/PVplugins/PVGeomechanicsWorkflowVolumeSurface.py
  geos-posp/src/PVplugins/PVGeomechanicsWorkflowVolumeSurfaceWell.py
  geos-posp/src/PVplugins/PVGeomechanicsWorkflowVolumeWell.py
  geos-posp/src/PVplugins/PVGeosLogReader.py
  geos-posp/src/PVplugins/PVMergeBlocksEnhanced.py
  geos-posp/src/PVplugins/PVMohrCirclePlot.py
  geos-posp/src/PVplugins/PVPythonViewConfigurator.py
  geos-posp/src/PVplugins/PVSurfaceGeomechanics.py
  geos-posp/src/PVplugins/PVTransferAttributesVolumeSurface.py
  geos-posp/src/PVplugins/__init__.py
Labels: flag: ready for review, type: bug

#77 refactor: Reformat to respect ruff rules
  .github/workflows/typing-check.yml
  geos-timehistory/src/geos/timehistory/__init__.py
  geos-timehistory/src/geos/timehistory/plot_time_history.py
  geos-trame/pyproject.toml
  geos-xml-tools/pyproject.toml
  geos-xml-tools/src/geos/xml_tools/__init__.py
  geos-xml-tools/src/geos/xml_tools/attribute_coverage.py
  geos-xml-tools/src/geos/xml_tools/command_line_parsers.py
  geos-xml-tools/src/geos/xml_tools/main.py
  geos-xml-tools/src/geos/xml_tools/regex_tools.py
  geos-xml-tools/src/geos/xml_tools/table_generator.py
  geos-xml-tools/src/geos/xml_tools/tests/generate_test_xml.py
  geos-xml-tools/src/geos/xml_tools/tests/test_manager.py
  geos-xml-tools/src/geos/xml_tools/unit_manager.py
  geos-xml-tools/src/geos/xml_tools/xml_formatter.py
  geos-xml-tools/src/geos/xml_tools/xml_processor.py
  geos-xml-tools/src/geos/xml_tools/xml_redundancy_check.py
  geos-xml-viewer/pyproject.toml
  geos-xml-viewer/src/PVplugins/deckReader.py
  hdf5-wrapper/pyproject.toml
  hdf5-wrapper/src/geos/hdf5_wrapper/__init__.py
  hdf5-wrapper/src/geos/hdf5_wrapper/use_example.py
  hdf5-wrapper/src/geos/hdf5_wrapper/wrapper.py
  hdf5-wrapper/src/geos/hdf5_wrapper/wrapper_tests.py
Labels: flag: ready for review, type: cleanup

#73 refactor: change dependency settup
  README.md
  geos-geomechanics/pyproject.toml
  geos-geomechanics/setup.py
  geos-geomechanics/src/geos/geomechanics/processing/geomechanicsCalculatorFunctions.py
  geos-posp/pyproject.toml
  geos-posp/setup.py
  geos-timehistory/pyproject.toml
  geos-timehistory/setup.py
Labels: flag: ready for review, dependencies

#79 ci: Modify doc CI to return error if warnings and update doc
  .github/workflows/doc-test.yml
  docs/conf.py
  docs/geos-geomechanics.rst
  docs/geos-xml-viewer.rst
  docs/geos_geomechanics_docs/home.rst
  docs/geos_geomechanics_docs/model.rst
  docs/geos_geomechanics_docs/processing.rst
  docs/geos_posp_docs/PVplugins.rst
  docs/geos_posp_docs/home.rst
  docs/geos_posp_docs/processing.rst
  docs/index.rst
  geos-geomechanics/src/geos/geomechanics/model/MohrCircle.py
  geos-geomechanics/src/geos/geomechanics/processing/geomechanicsCalculatorFunctions.py
  geos-posp/src/PVplugins/PVGeosLogReader.py
  geos-posp/src/geos_posp/filters/GeosBlockMerge.py
  geos-xml-tools/src/geos/xml_tools/regex_tools.py
  geos-xml-viewer/src/PVPlugins/__init__.py
  geos-xml-viewer/src/PVPlugins/deckReader.py
  geos-xml-viewer/src/PVPlugins/geostkParaviewPlugin.py
  geos-xml-viewer/src/PVPlugins/py.typed
  geos-xml-viewer/src/geos_xml_viewer/algorithms/deck.py
  geos-xml-viewer/src/geos_xml_viewer/bin/exporter.py
  geos-xml-viewer/src/geos_xml_viewer/bin/modifier.py
  geos-xml-viewer/src/geos_xml_viewer/bin/splitter.py
  geos-xml-viewer/src/geos_xml_viewer/bin/viewer.py
  geos-xml-viewer/src/geos_xml_viewer/filters/geosDeckReader.py
Labels: flag: ready for review, type: documentation, type: ci

#82 ci: Upgrade github actions
  .github/workflows/python-package.yml
  .github/workflows/typing-check.yml
  geos-geomechanics/src/geos/geomechanics/model/MohrCircle.py
Labels: flag: ready for review, type: ci
