Repository GEOS-DEV/geosPythonPackages, pull requests merged in 2025-08, with the labels that each got.

#109 feat: improve and update of geos-mesh utils functions
  geos-mesh/src/geos/mesh/utils/arrayHelpers.py
  geos-mesh/src/geos/mesh/utils/arrayModifiers.py
  geos-mesh/src/geos/mesh/utils/multiblockModifiers.py
  geos-mesh/tests/conftest.py
  geos-mesh/tests/data/displacedFaultempty.vtm
  geos-mesh/tests/data/domain_res5_id_empty.vtu
  geos-mesh/tests/data/fracture_res5_id_empty.vtu
  geos-mesh/tests/test_arrayHelpers.py
  geos-mesh/tests/test_arrayModifiers.py
  geos-posp/src/PVplugins/PVAttributeMapping.py
  geos-posp/src/geos_posp/filters/AttributeMappingFromCellCoords.py
  geos-posp/src/geos_posp/filters/GeosBlockMerge.py
Labels: flag: ready for review, type: feature, type: cleanup

#105 feat: add FillPartialArrays vtk filter and paraview plugin
  docs/geos_mesh_docs/processing.rst
  docs/geos_pv_docs/processing.rst
  geos-mesh/src/geos/mesh/processing/FillPartialArrays.py
  geos-mesh/src/geos/mesh/utils/arrayModifiers.py
  geos-mesh/tests/test_FillPartialArrays.py
  geos-mesh/tests/test_arrayModifiers.py
  geos-pv/src/geos/pv/plugins/PVFillPartialArrays.py
Labels: flag: ready for review, type: feature

#127 fix: Remove geos prep and update pyproject maintainers
  geos-geomechanics/pyproject.toml
  geos-mesh/pyproject.toml
  geos-posp/pyproject.toml
  geos-prep/pyproject.toml
  geos-pv/pyproject.toml
  geos-trame/pyproject.toml
  geos-utils/pyproject.toml
  geos-xml-tools/pyproject.toml
  geos-xml-viewer/pyproject.toml
Labels: flag: ready for review, type: bug
