Repository GEOS-DEV/geosPythonPackages, pull requests merged in 2025-09, with the labels that each got.

#134 fix: Secure multiBlockDataSet parsing.
  geos-mesh/src/geos/mesh/utils/arrayHelpers.py
  geos-mesh/src/geos/mesh/utils/arrayModifiers.py
  geos-mesh/src/geos/mesh/utils/multiblockHelpers.py
  geos-mesh/tests/data/displacedFault.vtm
  geos-mesh/tests/data/displacedFaultempty.vtm
  geos-mesh/tests/test_arrayModifiers.py
  geos-mesh/tests/test_multiblockHelpers.py
Labels: flag: ready for review, type: bug, type: cleanup

#138 fix: Clean verbosity in the function fillAllPartialAttributes
  geos-mesh/src/geos/mesh/utils/arrayModifiers.py
Labels: flag: ready for review, type: cleanup

#137 feat: Create the PV plugin wrapping ClipToMainFrame
  docs/geos_pv_docs/processing.rst
  geos-mesh/src/geos/mesh/processing/ClipToMainFrame.py
  geos-mesh/src/geos/mesh/utils/genericHelpers.py
  geos-mesh/tests/test_clipToMainFrame.py
  geos-pv/src/geos/pv/plugins/PVClipToMainFrame.py
Labels: flag: ready for review, type: feature

#128 refactor: Move `PVAttributeMapping`to geos-pv and create corresponding VTK filter in geos-mesh
  docs/geos_mesh_docs/processing.rst
  docs/geos_posp_docs/PVplugins.rst
  docs/geos_posp_docs/filters.rst
  docs/geos_pv_docs/processing.rst
  geos-mesh/src/geos/mesh/processing/AttributeMapping.py
  geos-mesh/src/geos/mesh/utils/arrayHelpers.py
  geos-mesh/src/geos/mesh/utils/arrayModifiers.py
  geos-mesh/src/geos/mesh/utils/multiblockModifiers.py
  geos-mesh/tests/conftest.py
  geos-mesh/tests/data/displacedFaultSurface.vtm
  geos-mesh/tests/data/displacedFaultemptySurface.vtm
  geos-mesh/tests/data/fracture_res5_id.vtp
  geos-mesh/tests/data/fracture_res5_id_empty.vtp
  geos-mesh/tests/test_AttributeMapping.py
  geos-mesh/tests/test_arrayHelpers.py
  geos-mesh/tests/test_arrayModifiers.py
  geos-posp/src/PVplugins/PVAttributeMapping.py
  geos-posp/src/PVplugins/PVTransferAttributesVolumeSurface.py
  geos-posp/src/geos_posp/filters/AttributeMappingFromCellCoords.py
  geos-posp/src/geos_posp/filters/AttributeMappingFromCellId.py
  geos-posp/src/geos_posp/filters/TransferAttributesVolumeSurface.py
  geos-posp/src/geos_posp/filters/VolumeSurfaceMeshMapper.py
  geos-pv/src/geos/pv/plugins/PVAttributeMapping.py
Labels: flag: ready for review, type: feature, type: cleanup
